/**
* <auto-generated>
* Code generated by LUISGen homeautomation.json -ts homeautomation -o 
* Tool github: https://github.com/microsoft/botbuilder-tools
* Changes may cause incorrect behavior and will be lost if the code is
* regenerated.
* </auto-generated>
*/ 
import {DateTimeSpec, IntentData, InstanceData, NumberWithUnits} from 'botbuilder-ai';

export enum Intents { 
    HomeAutomation_TurnOff = "HomeAutomation_TurnOff",
    HomeAutomation_TurnOn = "HomeAutomation_TurnOn",
    None = "None"
};

export interface _Intents { 
    HomeAutomation_TurnOff: IntentData;
    HomeAutomation_TurnOn: IntentData;
    None: IntentData;
};

export interface _Instance {
    HomeAutomation_Device?: InstanceData[];
    HomeAutomation_Operation?: InstanceData[];
    HomeAutomation_Room?: InstanceData[];
}

export interface _Entities {
    // Simple entities
    HomeAutomation_Device?: string[];
    HomeAutomation_Operation?: string[];
    HomeAutomation_Room?: string[];
    $instance : _Instance;
}

export interface homeautomation {
    text: string;
    alteredText?: string;
    intents: _Intents;
    entities: _Entities;
    [propName: string]: any;
}
